version: '3.8'
services:
  mysql:
    image: mysql:8.1
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: spring_quickly
      MYSQL_USER: bion
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --default-authentication-plugin=mysql_native_password
